[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "crypto>=1.4.1",
    "flask>=3.1.0",
    "numpy>=2.2.5",
    "pandas>=2.2.3",
    "pycryptodome>=3.22.0",
    "scikit-learn>=1.6.1",
]
